# .github/workflows/build.yaml
name: Build CI Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup gRPC
        # You may pin to the exact commit or the version.
        # uses: eWaterCycle/setup-grpc@029a9610a30c1ba8427a15c0b3be7f9377d39d3a
        uses: eWaterCycle/setup-grpc@v5
#         with:
          # Version of grpc to setup
#           grpc-version: # optional, default is 1.30.2
          # Used to pull grpc distributions from eWaterCycle/grpc-versions. Since there's a default, this is typically not supplied by the user.
#           token: # optional, default is ${{ github.token }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions

      - name: Run tox
        run: tox

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v3
#        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
#          fail_ci_if_error: true
